### ISSUE TITLE
Post Apocalyptic Shelter does not load

### ISSUE THREAD

**Issue by dominateeye** [DestinationHome/Destination-Home-Online#116]
**Describe the bug**
Attempting to travel to the Post Apocalyptic Shelter Personal Space fails, as the game gets stuck on the "Downloading and preparing scene" part of the loading screen.

**To Reproduce**

1. Go to Personal Spaces
2. Click on Post Apocalyptic Shelter and download it
3. Click on Post Apocalyptic Shelter again to go to the Space
4. Fail to load the Space

**Expected behavior**
The Personal Space should load.

**Screenshots & Video Documentation**
N/A

# Client Information:
**Region:** SCEA
**Country:** USA
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
I remember this space being a blank entry in Beta 1. It is no longer a blank entry, but the space itself may still not be in the game.

**Comment by NagatoDEV** [comment]
Can you provide a picture of this scene? I will need to check if we have this data. We could have the description meta-data up. However the actual scene we might not have them in our servers

**Comment by NagatoDEV** [comment]
Hi, @dominateeye clear your **cache** & see if you can load the Post Apocalyptic Shelter now. If the scene works please close out this ticket. 

![NPIA00005_screenshot_2023_04_07_12_38_30](https://user-images.githubusercontent.com/67494727/230645982-0295315b-cd90-4647-a86b-2f73d179c3fb.jpg)

**Comment by BJHBNade** [comment]
i have the same issue it will not work

**Comment by dominateeye** [comment]
After clearing my cache, it does work for me now. @BJHBNade, try clearing your cache by pressing Start -> Settings -> Cache Settings. Not sure if that works on emulator, but it works on PS3.

Thanks @NagatoDEV!
