### ISSUE TITLE
Items dont stay in storage 

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#118]
**Describe the bug**
When you move your inventory items such as furniture into storage they don't stay there. Once you reboot Home they're back in your main inventory. 

**To Reproduce**
1.Select which item you want in storage. 
2. Exit to the navigation screen.
3. Quit Home
4. Start Home
5. Open your inventory and the items have appeared back in your main inventory list

**Expected behavior**
This will move your selected it items back into your main inventory storage category. 

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** SCEE
**Country:** 
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by I-Knight-I** [comment]
Should be fixed now. Please re-open if not
