### ISSUE TITLE
IDEA / Suggestion: Online Game Ranking Discord

### ISSUE THREAD

**Issue by Patsoes** [DestinationHome/Destination-Home-Online#121]
I have an idea for Discord regarding game scores in Home Online.

We could have a discord # chat topic where we can share our game scores like arcade games etc (Ice Breaker, Bowling, ... ) And have them catogarized by game type. In here we can share our high scores within the community on discord and hopefully start to be competetive if we like. Beat eachothers highscores and having the highscore pinned or displayed in the discord somehow. Since online scoreboards do not function all the time or being unpresent. This could be a way to keep the highscores stored and displayed for everyone in the discord server. 

This is much easier to set up and doesn't break any rules of copyright of preservation since this is outside of home.

Lmk what you think.

**Comment by MrJunez** [comment]
I think this is better to put in somewhere in the discord as a suggestion rather than here but don't get me wrong. It seems like a good idea! just not in the right area for people to see as this area revolves around any issues people encounter in the game.

**Comment by Patsoes** [comment]
I asked a moderator / helper where this kind of stuff should belong and he said it would be fine to discuss the topic over here but was unsure himself. Although, if managers says otherwise, i'll move it to somewhere else
