### ISSUE TITLE
Playground Boombox furniture item doesn't work

### ISSUE THREAD

**Issue by GhostPSHOME** [DestinationHome/Destination-Home-Online#123]
**Describe the bug**
My Playground Boombox doesn't play any music when placed in a private space

**To Reproduce**
1. Place Playground Boombox in a private space
2. Click Play
3. No music can be heard

**Expected behavior**
If I remember correctly it should play the whole Playground soundtrack

# Client Information:
**Region:** SCEE
**Country:** Poland
**Platform:** PS3
**Firmware Type:** OFW

**Comment by BJHBNade** [comment]
seams none of the boom boxes do it may be a streaming issue that the urls are no longer available

**Comment by dominateeye** [comment]
See my issue on this subject from Closed Beta 1, which I reopened a few days ago: #26
