### ISSUE TITLE
Nighttime Estate Hollywood Hills

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#126]
**Describe the bug**
Will not download to enter space

**To Reproduce**

**Expected behavior**

**Screenshots & Video Documentation**
![20230406_125914](https://user-images.githubusercontent.com/108475784/230531657-2571750b-ee56-4c99-b663-d9db6aa34fd3.jpg)

# Client Information:
**Region:** [SCEA]
**Country:** [North America]
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Hi @Tiff2serious you can at least boot into the space now, please clear your cache and see if you can run into the Nighttime Estate Hollywood Hills.

![NPIA00005_screenshot_2023_04_08_20_24_35](https://user-images.githubusercontent.com/67494727/230748277-3f062355-e510-4eb7-9d2e-4566ac7ae8ad.jpg)

**Comment by Tiff2serious** [comment]
Yes! It worked :)
