### ISSUE TITLE
Luxury Race Box

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#132]
**Describe the bug**
Stuck on load screen, waited 15 min till I decided to restart game.
![20230404_110544](https://user-images.githubusercontent.com/108475784/230582910-250d5ebb-64eb-4ffa-bf21-5e7bb2b24980.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
                       [SCEA]
**Country:** [North America] 
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by BJHBNade** [comment]
same scene wont load just stuck on Downloading and preparing scene

**Comment by NagatoDEV** [comment]
I can boot into the space can you please check here as well if you can after clearing cache.

![NPIA00005_screenshot_2023_04_16_16_17_29](https://user-images.githubusercontent.com/67494727/232339874-bb8248f9-0d55-4804-9558-a5721404bcd8.jpg)
