### ISSUE TITLE
Moon Forest Apartment 

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#133]
**Describe the bug**
Missing Thumbnail, template, will not load
![20230404_113401](https://user-images.githubusercontent.com/108475784/230583726-f23e9847-0cb8-4454-b9e8-784366ba1d9d.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** [SCEA]
**Country:** [North America] 
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
@Tiff2serious Please clear your cache, and see if you can enter this scene. If so please close out this ticket. Thank you.

![NPIA00005_screenshot_2023_04_11_20_13_46](https://user-images.githubusercontent.com/67494727/231315609-639e9228-fb1d-4c23-9977-47042d9057d6.jpg)

**Comment by Tiff2serious** [comment]
Okay I'll check now

**Comment by Tiff2serious** [comment]
> @Tiff2serious Please clear your cache, and see if you can enter this scene. If so please close out this ticket. Thank you.
> 
> ![NPIA00005_screenshot_2023_04_11_20_13_46](https://user-images.githubusercontent.com/67494727/231315609-639e9228-fb1d-4c23-9977-47042d9057d6.jpg)
> 

I cleared cache, and it ended up stuck on load screen.

**Comment by xJeris** [comment]
I also can only get to loading screen for this apartment.

**Comment by BJHBNade** [comment]
still gets stuck on downloading and preparing scene

**Comment by NagatoDEV** [comment]
@xJeris @BJHBNade @Tiff2serious Can you guys check on this scene now.

**Comment by Tiff2serious** [comment]
> @xJeris @BJHBNade @Tiff2serious Can you guys check on this scene now.
> 

Sure

**Comment by BJHBNade** [comment]
looks like this loads now rewards in the space do not work though but at least the space is loading now!!

**Comment by xJeris** [comment]
@NagatoDEV I am able to enter the space now on ps3. The fire looks funny. I dont remember if it is supposed to just be white smoke. Do you want separate tickets for other issues like this?
![mf1](https://user-images.githubusercontent.com/85350673/232314518-cdee6627-d48b-4b26-8b4f-8214205c182a.jpg)

**Comment by NagatoDEV** [comment]
Huh, seems to be a texture bug... I might have to look more into this.

**Comment by NagatoDEV** [comment]
@BJHBNade @xJeris @Tiff2serious Clear cache and try again on my end the texture bugs are fixed.
