### ISSUE TITLE
Superstar Jetsetter Private Plane 

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#134]
**Describe the bug**
Missing thumbnail, template, will not load.
![20230404_113422](https://user-images.githubusercontent.com/108475784/230584217-01edfb54-7b05-4caf-bed6-592700822740.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** [SCEA]
**Country:** [North America] 
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Hi, @Tiff2serious you should be able to boot into the **Superstar Jetsetter Private Plane** scene, however, we are working on video content to be active in the scene.

![NPIA00005_screenshot_2023_04_08_10_44_37](https://user-images.githubusercontent.com/67494727/230727510-91d155b6-61d5-490c-97ad-d92eaad3f282.jpg)

**Comment by I-Knight-I** [comment]
![image](https://user-images.githubusercontent.com/26165117/230729181-08ba00bf-6d51-4984-8e89-e6437997f3fc.png)

Videos and images now work too
