### ISSUE TITLE
After Server Disconnect Storage Items Reset.

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#136]
**Describe the bug**
After a disconnection for what ever reason it resets your inventory items back to storage. I've noticed this more with clothing items. 

**To Reproduce**

1. Server Disconnection
2. Go to clothing inventory 
3. Some clothing that was in your main inventory is now in storage 

**Expected behavior**
Some items would send themselves back to storage. 

# Client Information:
**Region:** SCEE
**Country:** 
**Platform:** PS3
**Firmware Type:** OFW

**Comment by dominateeye** [comment]
This seems a very closely related issue to #118, would it be helpful to merge this issue into that one?

**Comment by Fritches** [comment]
As long as its being investigated I don't mind if it gets merged. On 9 Apr 2023 11:48, Andrew Ferguson ***@***.***> wrote:
This seems a very closely related issue to #118, would it be helpful to merge this issue into that one?

**Comment by Fritches** [comment]
It's not quite the same, #118 refers to when you actively put items in storage e.g anime furniture they return into main storage once you log back into home.

This one #136 refers to the instance of a disconnect of what ever reason some if not most of your items reset and get moved into storage.

**Comment by I-Knight-I** [comment]
Should be fixed.
