### ISSUE TITLE
E sys_net: Socket error ENOTCONN E SYS: 'sys_net_bnet_shutdown' failed with 0xffffffc7 : -SYS_NET_ENOTCONN [1]

### ISSUE THREAD

**Issue by TylerJaacks** [DestinationHome/Destination-Home-Online#139]
**Describe the bug**

**To Reproduce**

1. Double click PlayStation Home

**Expected behavior**
Connects to PlayStation Home

**Screenshots & Video Documentation**
![Screenshot 2023-04-08 181517](https://user-images.githubusercontent.com/1505374/230747826-fd02d02c-a574-4f56-8ce6-1b76b83a17d5.png)

# Client Information:
**Region:** SCEA
**Country:** USA
**Platform:** RPCS3
**Firmware Type:** OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

[RPCS3.log](https://github.com/DestinationHome/Destination-Home-Online/files/11184508/RPCS3.log)

**Comment by NagatoDEV** [comment]
Have you been whitelisted @TylerJaacks if not please make a ticket on the Discord.

**Comment by TylerJaacks** [comment]
So I think it was an issue with my VPN cause it is working now.
