### ISSUE TITLE
Sodium 2 Mini-game Doesn't Work

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#140]
**Describe the bug**
In the Sodium 2 space the mini-game doesn't work. 
**To Reproduce**

1. Go to Sodium 2
2. Head to the Sodium 2 racer
3. Click the mini-game
4. Nothing happens 

**Expected behavior**
The mini-game will not load. 

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** SCEE
**Country:** 
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Sodium 2 will need to be fully RE by the Destination Home Team, and is essentially a side-project that will need to be analyzed on it's own. We will keep this ticket open, and will update this during our beta testing phase.

**Comment by xJeris** [comment]
Sodium 2 is now working and available on nav.
