### ISSUE TITLE
Playground Music

### ISSUE THREAD

**Issue by PSG51** [DestinationHome/Destination-Home-Online#145]
The Playground its music does not work for both the stage and the rooftop.

I walked to both of those area ls and i didn't hear any music.

Region: Europe 
Country: Netherlands
Platform: PS3
Firmware Type: OFW

**Comment by NagatoDEV** [comment]
@PSG51 This bug has been fixed, please clear your cache data and re-enter The Playground. Here is a small clip of the original music playing in The Playground. 

https://user-images.githubusercontent.com/67494727/231204867-e34f6051-92cb-40e4-8720-868c840ecbc7.mp4
