### ISSUE TITLE
Dream Yacht wont load

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#147]
**Describe the bug**
The Lockwood Dream Yacht personal space won't load. 

**To Reproduce**

1. Go to the home menu
2. Go to your personal space folder
3. Locate the Dream Yacht
4. Click on it to navigate to the space
5. The loading process will begin
6. After the initial loading process has done it'll then load a picture of the yacht with the word "Loading". 
7. I've left it for over 10 minutes and nothing happens so I have to restart Home. 

**Expected behavior**
It will try to load but gets stuck on the yacht background with the word "Loading". I've left it for upwards of 10 minutes and nothing happens so I have to restart Home. 

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 
![DSC_0490](https://user-images.githubusercontent.com/129792409/231302834-2ae21c9c-df14-4a60-a338-a113252265d2.JPG)

# Client Information:
**Region:** SCEE
**Country:** 
**Platform:** PS3
**Firmware Type:** OFW

**Comment by NagatoDEV** [comment]
Closing this ticket out as we have another one open: https://github.com/DestinationHome/Destination-Home-Online/issues/125
