### ISSUE TITLE
Lock-a-doodle Studio Apartment - Does Not Download

### ISSUE THREAD

**Issue by xJeris** [DestinationHome/Destination-Home-Online#152]
**Describe the bug**
When attempting to download the space from the My Spaces menu, it will not download.

**To Reproduce**

1. Go to 'My Spaces'
2. Click on 'Download' for the 'Lock-a-doodle Studio' apartment
3. It will begin then stop immediately.

**Expected behavior**
Space should complete downloading and then allow you to visit it.

**Screenshots & Video Documentation**
![lockadoodle1](https://user-images.githubusercontent.com/85350673/231598962-ecf49d10-2107-4f9c-88b6-f420dbbd985d.jpg)

# Client Information:
**Region:** [SCEA]
**Country:**  US
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Comment by I-Knight-I** [comment]
Please use #39
