### ISSUE TITLE
Neptune Suite Apartment - Features Not Working

### ISSUE THREAD

**Issue by xJeris** [DestinationHome/Destination-Home-Online#156]
**Describe the bug**
1. "Scramble" Game screen is blank, and no prompt to play.
2. "Blast Zone!" game area is blank and no prompt to play.
3. "Blast Zone! Scoreboard" blank.

**To Reproduce**
1. Go to 'Neptune Suite' apartment
2. Visit Blast Zone! area. No prompt for either game or scoreboard.

1. Go to 'Neptune Suite' apartment
2. Visit video screen near firepit area. No prompt for scramble game

**Expected behavior**
Game prompts should appear and allow you to interact.

**Screenshots & Video Documentation**
Old walkthrough video shows functionality.
Timestamps: Blast Zone! 2:09, Scramble 1:14
https://www.youtube.com/watch?v=XvqnGYCrh10

1. Go to 'Neptune Suite' apartment
2. Visit Blast Zone! area. No prompt for either game or scoreboard.

# Client Information:
Region: [SCEA]
Country: US
Platform: [PS3]
Firmware Type: [OFW]

**Comment by NagatoDEV** [comment]
![NPIA00005_screenshot_2023_04_17_16_31_03](https://user-images.githubusercontent.com/67494727/232603494-3af1c333-6fa7-43ff-bada-e216666ca337.png)


- Clear cache @xJeris the minigame should boot, this was tested on RPCS3. If this game works please close out this ticket.

**Comment by xJeris** [comment]
@NagatoDEV 
Scramble - Not Working
Blast Zone! - Working
Blast Zone! Scoreboard - Working

**Comment by xJeris** [comment]
@NagatoDEV 
Scramble - Working
