### ISSUE TITLE
Cutteridge estate mini game 

### ISSUE THREAD

**Issue by yountj55** [DestinationHome/Destination-Home-Online#165]
**Describe the bug*
I completed “read from the moulding manuscript” upon lighting all 10 candles, freezes the ghost in place & no reward given. 

**To Reproduce**
1. Play “read from the moulding manuscript” mini game
2. Light all 10 candles

**Expected behavior**
the ritual completes, rewarding a ghost outfit.
 
**Screenshots & Video Documentation**
I didn’t grab any screenshots or a video, but I can if needed! 

# Client Information:
**Region:** [SCEA]
**Country:** NA 
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Additional context**
Never received reward, game seemed to freeze once completed & couldn’t play it again afterwards.

**Comment by Tertie** [comment]
To add to this report:
-I finished the candle minigame, and also did not receive the outfit.  But am not locked out of the minigame like OP is.
-I've completed the other minigames in the space for the 3 relics (Jessamine's doll, Clara's skull, and Jasper's scythe).  However only the doll was rewarded.  Not sure if the other 2 games have rewards.  And am unable to complete the activity under the stairs after collecting the 3 relics.

Region: [SCEA]
Country: NA
Platform: [PS3]
Firmware Type: [OFW]

**Comment by xJeris** [comment]
I heard in discord this might be working now? Can people confirm? @yountj55 @Tertie

**Comment by yountj55** [comment]
@xJeris Oh, good deal. I never saw Tertie's added comment either, I will be able to try after work (just a few hours left!) If everything seems good, I will close this as completed!

**Comment by Tertie** [comment]
@xjeris someone in discord today said the minigames are working, I'm going to reattempt later

**Comment by yountj55** [comment]
I have also played all mini games. Completed all rituals & received all rewards! Everything seems fine, nice work & thank you!
