### ISSUE TITLE
Waterfall terrace fishing game

### ISSUE THREAD

**Issue by yountj55** [DestinationHome/Destination-Home-Online#168]
**Describe the bug*
looks like the game can be played but I’m not able to press X on “play”

**To Reproduce**
Enter waterfall terrace, to the left of spawn is a fishing pole mini game. 

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** [SCEA]
**Country:** NA
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
@yountj55 Please, can you check out if the minigame is working. Of course please clear cache first it it works please close out this ticket.
![NPIA00005_screenshot_2023_04_17_16_39_24](https://user-images.githubusercontent.com/67494727/232626679-62717d38-52a8-4acc-bde6-d24961058fd2.jpg)
![NPIA00005_screenshot_2023_04_17_16_39_14](https://user-images.githubusercontent.com/67494727/232626705-5d96c55c-b93e-428f-8973-adf18e7ed353.jpg)

**Comment by xJeris** [comment]
Fishing game works for me. The leaderboard does not work however.

**Comment by yountj55** [comment]
Issue is now resolved & playable,thank you!

**Comment by Sin-Shadow-Fox** [comment]
It seems lures can't be unlocked and fish can't be mastered even after clearing cache.
