### ISSUE TITLE
Tron Space issues

### ISSUE THREAD

**Issue by BJHBNade** [DestinationHome/Destination-Home-Online#176]
**Describe the bug**
cannot go to second floor

**To Reproduce**
try to use the teleporters

**Expected behavior**
ability to go to second floor
**Screenshots & Video Documentation**
![image](https://user-images.githubusercontent.com/243883/232177057-319f8ac4-46fe-4408-b461-4fa489a3c489.png)

![image](https://user-images.githubusercontent.com/243883/232177038-7574d4a6-71c4-4010-a0cb-45915092cf28.png)

# Client Information:
**Region:** [SCEA]
**Country:** 
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by Toykyle** [comment]
Can you try the teleporter now? Should hopefully be fixed. You'd want to clear your cache for it to take effect.

**Comment by BJHBNade** [comment]
yes this is working now thanks
