### ISSUE TITLE
Lakeside Log Cabin

### ISSUE THREAD

**Issue by judo-boy-italia** [DestinationHome/Destination-Home-Online#177]
**Describe the bug**
The room is present in the navigator, the download is recognized but the upload never starts

**To Reproduce**
start the menu, personal spaces, click on: Lakeside Log Cabin, start a loading that never ends

**Expected behavior**
Obviously uploading this personal space that I bought years ago

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
Region: [SCEE]
Country: Italy
Platform: [PS3]
Firmware Type: [?]

**Additional context**
-

**Comment by NagatoDEV** [comment]
Did you clear cache as this space has already been fixed? Please check this link here: https://github.com/DestinationHome/Destination-Home-Online/issues/142

**Comment by judo-boy-italia** [comment]
Now everything is in place, and new surprises have also appeared in the personal menu, too many years have passed and I didn't remember many things. Thank you very much Nagato!
