### ISSUE TITLE
MIB personal space Interactive items not working

### ISSUE THREAD

**Issue by BJHBNade** [DestinationHome/Destination-Home-Online#182]
**Describe the bug**
MIB rapid transport system does not work

**Expected behavior**
menu for teleport locations

**Screenshots & Video Documentation**
![image](https://user-images.githubusercontent.com/243883/232230924-a5e5d5fd-db55-44a6-9c39-26b77769d788.png)
![image](https://user-images.githubusercontent.com/243883/232230940-b670f6fb-8fe0-4c68-9443-ef6f322dc479.png)

# Client Information:
**Region:** [SCEA]
**Country:** US
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Hi @BJHBNade please clear your cache, the **MIB™ Rapid Transport** object is fixed.

![NPIA00005_screenshot_2023_04_29_12_13_24](https://user-images.githubusercontent.com/67494727/235312607-496c2352-8540-4c2a-8313-6ee85740d174.png)

**Comment by NagatoDEV** [comment]
If everything is working @BJHBNade please close out this issue.

**Comment by BJHBNade** [comment]
looks like it works closing
