### ISSUE TITLE
Public spaces being added to favorite doesn't save when re logging back on Home

### ISSUE THREAD

**Issue by Junior1441** [DestinationHome/Destination-Home-Online#184]
Describe the bug
Recently when the update added the Konami Penthouse, Seaside of Memories, Irem Square and few more, when attempting to save those three it marks them as favorite. But when I go off home and log back in, it doesn't show it has been saved to favorite. And to add on top of that, when I removed one space that was in the favorite it shows I still have it when I log back on Home.

To Reproduce

1. Go to Konami Penthouse, Irem Square and Seaside of Memories
2. Click on them and add to favorite 
3. Quit Home and log back in
4. Sees it not been added to favorite despite you done so.

Expected behavior
The public spaces should have been saved to favorite and not disappear when having to log back on Home 

Client Information:
Region: SCEE
Country: NA
Platform: PS3
Firmware Type: HFW

**Comment by blake1725** [comment]
multiple people have this where faves remove themselves after logging out New faves and recently visited disappear

**Comment by Junior1441** [comment]
:point_up_2:

**Comment by blake1725** [comment]
nothing saves for me default apartment resets after log out 
my Navigator settings reset like time stamp and display status 
and faves and recently visited
name colour resets 
i have tried playing on OFW that didnt work
i tried delete ticket list from home files on MM that didnt work

**Comment by I-Knight-I** [comment]
This has been fixed. Reopen if it appears again
