### ISSUE TITLE
Winter Wonderland Apartment not downloading

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#186]
**Describe the bug**
I can't get my Winter Wonderland apartment to download. 

**To Reproduce**

1. Go to the navigation home screen 
2. Go to your Apartments
3. Locate Winter Wonderland Apartment 
4. Try to download
5. Download failed

**Expected behavior**
For the space to download and be able to go to. 

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** SCEE
**Country:** 
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by Fritches** [comment]
![DSC_0495](https://user-images.githubusercontent.com/129792409/232562536-c3b81953-e7d7-4226-b49a-7bd90b1e0d14.JPG)

The image was there when u reported the problem but gone now, I will restart home to see if that loads it back.

**Comment by NagatoDEV** [comment]
Will need to do research of all minigames in this space as some are not loading. So I will keep this ticket open, however we are able to boot into the space at least.

**Comment by Fritches** [comment]
Do you want me to close the other ticket and reopen this ticket?
