### ISSUE TITLE
Nightlife Lounge Apartment - Missing XMB Icon

### ISSUE THREAD

**Issue by xJeris** [DestinationHome/Destination-Home-Online#187]
**Describe the bug**
Icon in XMB is missing. Space works fine.

**To Reproduce**

1. Go to Spaces on XMB
2. View the Nightlife Lounge Apartment
3. No icon

**Expected behavior**
Icon for the apartment should be visible.

**Screenshots & Video Documentation**
![nightlife1](https://user-images.githubusercontent.com/85350673/232578091-5f1667d4-02bb-45ac-a589-7fc3069f0ca5.jpg)

# Client Information:
**Region:** [SCEA]
**Country:** [US]
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Comment by NagatoDEV** [comment]
Icon is now fixed.
