### ISSUE TITLE
Blaster's Paradise Tank Top mini-game wont load.

### ISSUE THREAD

**Issue by Fritches** [DestinationHome/Destination-Home-Online#196]
**Describe the bug**
The Tank Top mini-game inside the Blaster's Paradise apartment will not load up. 

**To Reproduce**

1. Go to Blaster's Paradise apartment 
2. Head to the Tank Top mini-game 
3. Try and play it
4. Nothing happens after repeated presses of "X" 

**Expected behavior**
Once you've highted the mini-game and pressed "X" the game should start to play. 

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** SCEE
**Country:** UK
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Hi @Fritches Please clear your cache to see if it loads now the minigame. 
![NPIA00005_screenshot_2023_04_28_19_50_46](https://user-images.githubusercontent.com/67494727/235271046-6b629c19-cb87-4488-a6b8-6cf0493748ba.png)
![NPIA00005_screenshot_2023_04_28_19_50_51](https://user-images.githubusercontent.com/67494727/235271049-97f89078-2a69-4451-a09e-95c8490dbf73.png)

**Comment by Fritches** [comment]
Thankyou :)
