### ISSUE TITLE
Furniture Item Freeze

### ISSUE THREAD

**Issue by PSG51** [DestinationHome/Destination-Home-Online#197]
**Describe the bug**
When i selected the Playground Boombox in the decorate space option, i get a freeze and the console forces me to restart ending up in a 'did not turn off properly' issue

**Expected behavior**
Console Freeze upon selecting Playground Boombox in decorate.

# Client Information:
**Region:** [SCEA, SCEE, SCEJ, SCEAsia, Other]
EU
**Country:**
Netherlands
**Platform:** [PS3, RPCS3]
PS3
**Firmware Type:** [OFW, HFW, CFW]
OFW

**Comment by I-Knight-I** [comment]
Duplicate of #26
