### ISSUE TITLE
Audi home terminal : impossible to access Audi technology experience

### ISSUE THREAD

**Issue by NecroHyR** [DestinationHome/Destination-Home-Online#199]
**Describe the bug**
Impossible to access the mini game "Audi technology experience" in the audi home terminal. When trying to access the minigame, there is a little window saying "Waiting to connect. Please wait..."

**To Reproduce**
- Go to the Audi Home teminal
- Get close to the Audi technology experience
- Click on X

**Expected behavior**
Getting into the menu of Audi technology experience.

**Screenshots & Video Documentation**

![Screenshot_5](https://user-images.githubusercontent.com/132080432/235188670-025eaade-bfd4-4234-8615-41f4805aa672.png)

# Client Information:
**Region:** 
SCEE
**Country:** 
France

**Platform:** 
RPSC3
**Firmware Type:** 
OFW

**Comment by BJHBNade** [comment]
same issue on ps3

**Comment by I-Knight-I** [comment]
This is intentional as Audi Technology Experience currently doesn't work, so we've disabled it.
