### ISSUE TITLE
Sodium Blimp does not load; gets stuck in a black screen

### ISSUE THREAD

**Issue by I-Knight-I** [DestinationHome/Destination-Home-Online#20]
**Describe the bug**
Sodium Blimp shows a black screen with a spinning loading wheel seemingly forever upon loading in. It goes away when in the Navigator, showing my character standing in a half-loaded version of the Space, but comes back upon exiting the Navigator

**To Reproduce**

1. Go to 'Sodium Blimp' apartment
2. See error

**Expected behavior**
Sodium Blimp loads

# Client Information:
**Region:** SCEA
**Country:** USA
**Firmware Version:** 4.89

**Comment by dominateeye** [comment]
Similar thing happening with Xi: Continuum and Xi: Continuum - Vertigo Apartment, except for those Spaces, there is a unique Xi: Continuum themed loading screen which doesn't allow you to access the Navigator by pressing Start for a few minutes after traveling there.

**Comment by I-Knight-I** [comment]
![image](https://github.com/DestinationHome/Destination-Home-Online/assets/26165117/d26b4dfc-a611-4b02-b61a-d1196e885d51)
Working.
