### ISSUE TITLE
message

### ISSUE THREAD

**Issue by Neri99** [DestinationHome/Destination-Home-Online#206]
rember awhile ago i said i got some weird message when logging in? it has just happened again i got a picture this time

![20230506_120024](https://user-images.githubusercontent.com/129874297/236620596-621f64e6-1fd0-4f82-a08b-743fd8b62910.jpg)

**Comment by NagatoDEV** [comment]
Was this on a new account? It's just the EULA screen, which is normal. If you have your saves, content, and other stuff working then you should be okay. @Neri99
