### ISSUE TITLE
Challenge icon missing from Navigator

### ISSUE THREAD

**Issue by blake1725** [DestinationHome/Destination-Home-Online#207]
![20230513_114423](https://github.com/DestinationHome/Destination-Home-Online/assets/132437520/3364a96f-f582-43d9-8fe2-0a57656d4f99)

**Comment by NagatoDEV** [comment]
Challenges are on our development roadmap, however right now it is not a main priority for our Closed Beta 2 phase.

Note, we will keep this ticket up for documentation purposes.
