### ISSUE TITLE
SIREN: Rewarded T-Shirt has haruka skirt thumbnail 

### ISSUE THREAD

**Issue by Neri99** [DestinationHome/Destination-Home-Online#208]
So in the 1st round you get rewarded a t shirt but in wardrobe it shows as a skirt

![20230520_145947 1](https://github.com/DestinationHome/Destination-Home-Online/assets/129874297/27cdb5bd-082f-4fdc-9381-f1909d5c1755)

**Comment by NagatoDEV** [comment]
Thank you for reporting this issue, I will be taking a look at this soon @Neri99

**Comment by Neri99** [comment]
fixed
