### ISSUE TITLE
Home square media 

### ISSUE THREAD

**Issue by blake1725** [DestinationHome/Destination-Home-Online#209]
Posters and media at HS show for NA but not EU

**Comment by NagatoDEV** [comment]
Can you provide an image of this error? Thanks. 

Later on today, I'll take a look at this issue. What is the **exact region** of your PSN account by the way?

**Comment by blake1725** [comment]
![346150692_298891775803000_7968347105769238680_n](https://github.com/DestinationHome/Destination-Home-Online/assets/132437520/e404e35e-0427-4a3d-8410-a96ac5726e94)

**Comment by blake1725** [comment]
im in the uk

**Comment by NagatoDEV** [comment]
Okay, thank you for letting me know I will work on this right now.

**Comment by blake1725** [comment]
just found out its all media at mui mui ship same problem

**Comment by NagatoDEV** [comment]
Try @blake1725 now, clear your cache for Home Square and resign back into your UK account.

**Comment by NagatoDEV** [comment]
@blake1725 For Mui Mui Ship is that the personal space or no? Please create another ticket for this issue as well. Thank you. :D

**Comment by I-Knight-I** [comment]
Please use #213
