### ISSUE TITLE
Male head item not loading.

### ISSUE THREAD

**Issue by yountj55** [DestinationHome/Destination-Home-Online#214]
There is one particular head item that doesn't load at all. It was added within the last request of clothing items. 

**to reproduce**
Go into wardrobe & find the head item that doesn't load. I believe it's the old snowman head. 

**Expected behavior**
To load onto avatar.
 
**Screenshots & Video 
Documentation**
![image](https://github.com/DestinationHome/Destination-Home-Online/assets/53020104/cb16efb4-39b0-44d1-a4f1-135f93d844cc)

# Client Information:
**Region:** [SCEA]
**Country:** NA
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Additional context**
In the photo above, you can see that the white hat above it just says loaded while the other item is highlighted.

**Comment by sixx6sics** [comment]
yes i have the same issue where the male snowman mask does not load
