### ISSUE TITLE
Network Error Z(11, -2)

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [DestinationHome/Destination-Home-Online#220]
**Describe the bug**
I'm getting Network Error Z(11, -2) (which I'm told is a whitelisting error) even though I'm enrolled and whitelisted.

**To Reproduce**

1. Turn on PS3
2. Click on PlayStation Home
3. Wait

**Expected behavior**
A few network errors followed by connection to PlayStation Home.

**Screenshots & Video Documentation**
![235767281-07280dd0-6069-4489-8b69-08a2acec2ad0](https://github.com/DestinationHome/Destination-Home-Online/assets/96899282/516f409b-83fb-4f32-9e40-6950245dd755)

# Client Information:
SCEA
America
PS3
OFW

**Additional context**
Some time late 5/1/2023 I starting getting Network Error Z(11, -2) and I made a ticket asking about the problem. After a month or so I was told that the network error was a white listing error and that I should enroll. However my ticket was closed before I could explain that I'm already enrolled and whitelisted.

The only thing that changed before i started getting the error was i swapped my PS3s video input from my normal TV to a portable TV Radio to test it for my mother (she likes old devices) Other than that nothing has changed: No updates, No new games/programs/music/pictures, Haven't moved or unplugged the PS3, Haven't changed or unplugged the Dualshock 3 controller, Haven't changed any of the PS3s settings or the home internet settings or provider.

**Comment by I-Knight-I** [comment]
This is not a bug. You're not whitelisted and I can't find an account associated with your username.
If you've left the server then you were unwhitelisted as the requirements for Closed Beta 2 are as follows:

- **Role:** Member (or above)
- **Account Age:** > 3 months
- **DH Member:** > 1 month
- **Warnings:** None

**Comment by Sin-Shadow-Fox** [comment]
> This is not a bug. You're not whitelisted and I can't find an account associated with your username. If you've left the server then you were unwhitelisted as the requirements for Closed Beta 2 are as follows:
> 
>     * **Role:** Member (or above)
> 
>     * **Account Age:** > 3 months
> 
>     * **DH Member:** > 1 month
> 
>     * **Warnings:** None

What? Why do i have to be a part of the discord? Wait i know how to solve this. What about the people who don't have discord? How do they get whitelisted? I'll just do that instead.

**Comment by I-Knight-I** [comment]
It is a **_Closed Beta_**. The current requirements are that people must be in our Discord so we can adequately and easily test, get community feedback, provide updates and experiment.

People will be able to join freely once we're in _**Open Beta**_.
