### ISSUE TITLE
Welcome screen shows on every login instead of only the first one

### ISSUE THREAD

**Issue by TsukiTheDwagon** [DestinationHome/Destination-Home-Online#228]
**Describe the bug**
The Welcome loading screen that only shows on the first time you log into home appears every time I log in.

**To Reproduce**

1. Log into home
2. Load past initial loading screen
3. See welcome screen somehow
4. I really don't know how you replicate seeing the welcome screen every log in. It seems that it doesn't happen to everyone, and for people experiencing the issue it just shows up

**Expected behavior**
The welcome screen does not appear on any login except the first.

**Screenshots & Video Documentation**
It's literally just the welcome screen

# Client Information:
**Region:** SCEA
**Country:** Canada
**Platform:** PS3
**Firmware Type:** OFW

**Additional context**
Feels like it could be related to user settings files in some way

**Comment by I-Knight-I** [comment]
What do you mean by 'welcome screen'? Can you take a screenshot?

**Comment by TsukiTheDwagon** [comment]
![welcome screen](https://github.com/DestinationHome/Destination-Home-Online/assets/38333752/db022757-a557-4508-baa7-fe8a34e52794)
This screen here, sorry

**Comment by TsukiTheDwagon** [comment]
Seems it's normal behavior, actually, from what the other devs are saying
