### ISSUE TITLE
japanese teahouse and country buss 

### ISSUE THREAD

**Issue by Amyym** [DestinationHome/Destination-Home-Online#231]
The japanese teahouse from granzilla and country chic tour bus from jam games refuse to download, also the LKWD venue apartment is broken.

**Comment by xJeris** [comment]
Moving these to existing threads.

https://github.com/DestinationHome/Destination-Home-Online/issues/39  Missing Spaces
https://github.com/DestinationHome/Destination-Home-Online/issues/201  LKWD
