### ISSUE TITLE
Region locked invites 

### ISSUE THREAD

**Issue by blake1725** [DestinationHome/Destination-Home-Online#235]
![IMG_20191104_215924](https://github.com/DestinationHome/Destination-Home-Online/assets/132437520/63e55074-d5e4-40d0-a716-a48eca0ae68c)
![IMG_20191104_215935](https://github.com/DestinationHome/Destination-Home-Online/assets/132437520/60aafe0c-d2a6-470f-b4d0-86b1c2e4e298)

NA cant invite or join EU at public  spaces and vice versa. only if its on the navi 
we can invite to apartments just not public space

**Comment by I-Knight-I** [comment]
Fixed.

**_Most_** spaces will now be global. There are some exceptions such as certain game spaces.
