### ISSUE TITLE
News Viewer unimplemented

### ISSUE THREAD

**Issue by jflame01** [DestinationHome/Destination-Home-Online#238]
**Describe the bug**
When entering the Cafe at the square, and choosing the option to view news it darkens the screen and freezes the game

**To Reproduce**
I entered the Cafe, choose a seat, as my character was drinking coffee I pressed Square to view the news, my screen then darkened and nothing appeared, I awaited a few moments and nothing appeared, I brought the menu up to travel to a separate location to fix the bug and it froze me game entirely.

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** North America
**Country:** United States of America
**Platform:** [PS3
**Firmware Type:** [OFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by NagatoDEV** [comment]
Can you provide a picture of the bug?

**Comment by CamoRF** [comment]
I can't reproduce this on RPCS3, was trying to get a screenshot and it just keeps saying you can't use the nav while in a game.

**Comment by I-Knight-I** [comment]
Fixed
