### ISSUE TITLE
Blank entries in Personal Spaces list

### ISSUE THREAD

**Issue by dominateeye** [DestinationHome/Destination-Home-Online#24]
**Describe the bug**

Two entries in my Personal Spaces list have titles of "...", no images, and no description box. The entries remain this way even after the list has fully loaded.

**To Reproduce**

1. Go to Navigator
2. Go to 'My Home'
3. Scroll down to 'My Spaces' and select it
4. Scroll down again to 'My Spaces' and select it
5. Scroll through the My Spaces list until you find a blank entry as described above

**Expected behavior**

All entries in the Personal Spaces list should contain information on a particular Space.

**Screenshots & Video Documentation**

![PXL_20221029_050941156](https://user-images.githubusercontent.com/22434263/198815412-5dd00311-d065-4e3a-944a-34f5fa9ccd1f.jpg)
![PXL_20221029_051003313](https://user-images.githubusercontent.com/22434263/198815413-aed4b1e2-eada-440e-b197-43b7fe957c5f.jpg)

# Client Information:
**Region:** SCEA
**Country:** United States of America
**Firmware Version:** 4.89

**PlayStation 3:** Yes
**Firmware Type:** OFW

**RPCS3:** No
**CPU:** N/A
**GPU:** N/A
**RAM:** N/A

**Additional context**

I know I had more Personal Spaces than this in my account. I theorize that these blank entries may correspond to some Spaces that are not yet on DH's servers.

**Comment by MrJunez** [comment]
Are you able to visit this personal space to see what it is or it won't let you?

**Comment by dominateeye** [comment]
I haven't done so yet out of concern for breaking something either on my end or on DH's end. If a dev team member wants me to try visiting the spaces and can monitor the server while I do so (both to ensure it doesn't melt down and also to see if any clues can be gleaned from the attempt), I am willing to give it a shot.

**Comment by I-Knight-I** [comment]
Missing spaces were:
- Playground Apartment (fixed)
- Post Apocalypse Apartment (fixed description + image but map is currently unavailable) [See #29]
