### ISSUE TITLE
Using real keyboard with RPCS3 doesn't accept letters and Backspace crashes the emulator

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [DestinationHome/Destination-Home-Online#25]
**Describe the bug**

When "Keyboard Handler" is set to "Basic" in RPCS3, Home accepts inputs from a real keyboard.  However, it doesn't accept any inputs that aren't letters or the space bar.  Additionally, using Backspace to delete around 20 characters from the keyboard prompt completely crashes RPCS3 with no errors in the log, the program "Not Responding" as well.

**To Reproduce**

Punctuation issue:
1. Go to any scene.
2. Press Triangle to open the keyboard prompt.
3. Attempt to type any punctuation, like commas, periods, plus signs, etc.

Crash issue:
1. Go to any scene.
2. Press Triangle to open the keyboard prompt.
3. Write out a message and then use Backspace to delete it.
4. Do this a second time and it'll crash roughly half-way through.

I have recreated the above issues many times, it is very easy.

**Expected behavior**

Punctuation should be accepted, allowing entering full sentences, and if you want to go back and delete characters, doing so shouldn't cause any issues.

**Screenshots & Video Documentation**

In the video, I type each row of a real USA keyboard.  Notice how only letters are accepted, even when using Shift.  Then after erasing some of the lines with Backspace, RPCS3 crashes.

https://user-images.githubusercontent.com/58268914/198817914-d05e2dbf-dcb6-4482-b0da-0a88d133d3e7.mp4

# Client Information:
**Region:** SCEA
**Country:** USA
**Firmware Version:** 4.89

**RPCS3:** v0.0.24-14208-1a9e38a1 (PSONE branch)
**CPU:** Intel Core i9-10900K
**GPU:** NVIDIA RTX 2080 Super
**RAM:** 64 GB DDR4

**Additional context**

Sometimes the crash will happen sooner, sometimes later.  When I recreated this the second time, it crashed after only a few deleted characters.

**Comment by I-Knight-I** [comment]
No longer seems to be an issue + is RPCS3 specific
