### ISSUE TITLE
Problem rewards Midways and others spaces

### ISSUE THREAD

**Issue by Br3iZHGaM3R** [DestinationHome/Destination-Home-Online#250]
Hello , 

Since that night I no longer earn rewards in the 3 Midways, is it general or is it just me?

Because this problem came after being disconnected from the PSN suddenly like that while I was walking around Park Meadows, then when I restarted the game I went to Midway to pass the time then while winning games I noticed that the rewards were no longer triggered, even on the board the level boxes are checked, but as soon as I change the map and come back, the checked boxes disappeared as if I had not played..

I restarted my console several times, I emptied the home cache several times, I deleted the Home data in the PS3 data utility, and nothing changed.

I logged in just now to see if between last night and now it had changed and no, it's still the same, I no longer earn rewards at Midway, I went to Aurora, I reached level 15 and 20 and I didn't get any rewards ..
### _### [EDIT] Concerning Aurora, the rewards were unlocked 2 days later as soon as I arrived on the map_

Could someone help me please?

# Customer Information:
**Region:** [SCEE]
**Country:** France
**Platform:** [PS3]
**Firmware Type:** [OFW]
![Price Big Foot - Level 8 - Midway 3 11-07-2023](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/d144ba57-5569-492e-b9b2-267b9a5217b2)

**Comment by CamoRF** [comment]
Closing issue as it's a duplicate, see [#263 ](https://github.com/DestinationHome/Destination-Home-Online/issues/263)
