### ISSUE TITLE
Can't delete saved avatars

### ISSUE THREAD

**Issue by LucentGinger** [DestinationHome/Destination-Home-Online#252]
**Describe the bug**
The avatars doesn't delete when you try to delete them from your saves or loads.

1. Go to 'wardrobe'
2. Click on 'Load/Save'
3. Scroll down to 'Save or Load'
4. Avatars not deleting error

**Expected behavior**
The avatars should be deleted when you delete them.

# Client Information:
**Region:** [SCEA]
**Country:** USA
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Additional context**
The avatar keeps showing up after you try to delete them.

**Comment by LucentGinger** [comment]
I have a video of the bug but I couldn't put it on here.

**Comment by CamoRF** [comment]
Known issue, there's also an issue where saved avatars can have a black thumbnail. A work around is to overwrite old slots and the new avatar will save with a fixed thumbnail.

**Comment by LucentGinger** [comment]
I tried that and it didn't work.

**Comment by LucentGinger** [comment]
Oh okay. Weird. I tried everything I could to delete the avatar that I had saved but nothing worked.

**Comment by I-Knight-I** [comment]
@LucentGinger Retest this please

**Comment by I-Knight-I** [comment]
Should be fixed
