### ISSUE TITLE
Siren - Ward of Despair Not Rewarding Me The Clothing

### ISSUE THREAD

**Issue by Junior1441** [DestinationHome/Destination-Home-Online#254]
I cleared the game solo where I had to pick up the lab coat and trouser and didn't get the reward after beating it. I believe it a bug where I am not rewarded with a clothing/outfit that I picked up and win the game.  Same with different scenarios that I had to complete the game, I still don't get any rewards for beating it or completing the objectives.  

Playing the game solo
complete the objectives 
Pick up the clothing piece from the basement to obtain them as as rewards

Once completing the game the rewards should have shown on the screen to say "You have received a reward" 

Client Information:
Region: SCEE
Country: NA
Platform:PS3
Firmware Type: HFW

All Rewards (loads slow):  https://stores.yourpshome.net/siren-blood-curse

**Comment by CamoRF** [comment]
I was able to get the clothing on RPCS3, longshot but maybe try clearing your cache?

**Comment by CamoRF** [comment]
I'm closing this issue as I've been able to test it on both PC and PS3 and the issue was the Acorn shop corrupting the TICKETS.LST file which is now fixed. If anyone still has this issue please delete your save and clear your cache and it should work.
