### ISSUE TITLE
Ward Of Despair reward 4 player bug

### ISSUE THREAD

**Issue by panos92-deg** [DestinationHome/Destination-Home-Online#255]
Hey,so i tried it several times possible before submitting it to make sure i aint wrong.So we tried the ward of despair couple times with some randoms and there is a reward,where u complete ward of despair with 4 people without anyone dying u get a reward,we did more than once as i said to make sure but its missing. Im on RPCS3

Reward:
<img width="551" alt="image" src="https://github.com/DestinationHome/Destination-Home-Online/assets/85350673/1c264b7d-4354-4547-b828-78bdd89d782d">

**Comment by CamoRF** [comment]
I was able to get the reward on RPCS3, longshot but maybe try clearing your cache?

**Comment by CamoRF** [comment]
I'm closing this issue as I've been able to test it on both PC and PS3 and the issue was the Acorn shop corrupting the TICKETS.LST file which is now fixed. If anyone still has this usse please delete your save and clear your cache and it should work.
