### ISSUE TITLE
Indie Park Scene Download Error

### ISSUE THREAD

**Issue by CamoRF** [DestinationHome/Destination-Home-Online#257]
**Describe the bug**
Indie Park scene cannot be downloaded via the Bowling Alley.

**To Reproduce**

1. Go to 'Bowling Alley'
2. Turn around immediately to the door/exit
3. Walk forward and attempt to download scene

**Expected behavior**
The scene should download without an error and the player should then be able to enter the new space after it downloads.

**Screenshots & Video Documentation**
![rpcs3 2023-07-17 20-01-41](https://github.com/DestinationHome/Destination-Home-Online/assets/113881920/036eaf80-f735-4ab3-b9eb-14c80e526b1f)

# Client Information:
**Region:** SCEA
**Country:** Australia
**Platform:** RPCS3
**Firmware Type:** OFW

**Additional context**
Downloading in background and/or trying over and over can get more of the scene to download but it will eventually still error out at some point.

**Comment by I-Knight-I** [comment]
We've intentionally disabled this server-side whilst we work on it
