### ISSUE TITLE
Inventory resetting for clothing and furniture

### ISSUE THREAD

**Issue by Br3iZHGaM3R** [DestinationHome/Destination-Home-Online#262]
At each connection to the Home, all the clothes and furnitures that you select as favorites disappear on their own, and for some go back to storage..

Is there a manipulation so that the clothes and furnitures selected in favorites remain in favorites after each reconnection on the Home ?

This problem only affects clothing and furnitures , the favorites selected in the inventory remain in favorites.

Region: [SCEE]
Country: [France]
Platform: [PS3]
Firmware type: [OFW]
PSN ID: Br3iZH-_GaM3R-

**Comment by CamoRF** [comment]
I'm clsoing this issue as it's due to a hardcoded limit with PS Home, try moving everything you don't use to storage and it should save and work fine. These are limits: 

500 clothing items, 
500 furniture
~60 portables
