### ISSUE TITLE
Br3iZHGaM3R: Rewards not working anywhere

### ISSUE THREAD

**Issue by Br3iZHGaM3R** [DestinationHome/Destination-Home-Online#263]
Hello, I report this problem because for several days I no longer earn any rewards anywhere in the Home.

I don't understand, before July 11, 2023 I was earning rewards everywhere I went and since July 12 it's over, I don't earn anything anymore..??

I deleted Home's save data, I deleted Home's cache, I deleted Home, I deleted the TICKET.LST file in the files, I did everything I was told to do but it didn't change anything.. I came back to OFW but the problems are still there and it's even worse and worse.. It's hopeless...

I show you some pictures, I do not know if it is necessary but I do it anyway

**Aurora I went from level 35 to level 61 and received no rewards**
![357306884_589406756673615_8282867359498481727_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/3fac9d15-0ee0-4692-8f80-636a0d3e0e3d)

**I finished my Ile Locco, I should have received King Muimui's reward and I did not receive it**
![357182499_1816396062109064_7505581957650072926_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/16722a21-b625-4e6b-9b69-5e5e144a75ba)
![356991024_592991012985339_742291174071557849_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/97e7baaf-a287-4bc5-a4ae-290d5c8ef80c)
![356967264_831413541909771_1085771814962846305_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/35976bdd-730d-4973-b278-b573f4a5eddd)

**I went for a dolphin race which I won, I should have received the blue horns and I did not receive them**
![357308518_238502542348245_3122187055005488906_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/8b2c4af0-6289-439a-972e-1a9f780f8737)
![356979091_261976723206854_6745547584287726684_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/2368c257-4a66-469f-9061-0ef8114a8193)
![11-228x228](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/f607ffdf-a9eb-47ac-9c7c-22f44a898d1d)

**At Park Acorn Meadoxws Summer, in the shop yesterday I was able to buy items and now I can't, when I buy one, it deducts my tickets but I don't receive the items, and when I leave home and when I come back to Home after leaving it, it indicates that I never bought the item same problem at Park Acorn meadows 4th July**
![357268281_3055995474695730_6864176083164580988_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/ac091c2b-cbf6-41f9-8a50-fc88078aa999)
![357267133_656432263050834_5577059068734836058_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/16cb39b6-44ac-4b88-b46c-474421fa9678)
![357321823_1616233498899106_7913488596659730261_n](https://github.com/DestinationHome/Destination-Home-Online/assets/139374431/c10dca6d-469c-4aa9-b41f-35330f6cec76)

**And finally, I went to Midway because I saw on the Discord that the games were fixed, which is true, but the game Blue Balls does not work and whether it is in Midway 1 2 and 3, when I win a game I do not receive any rewards**

Am I the only Home player having all these problems ?

Can someone please let me know ? Thanks in advance

Region: [SCEE]
Country: [France]
Platform: [PS3]
Firmware Type: [OFW]
PSN ID: Br3iZH-_GaM3R-

**Comment by CamoRF** [comment]
Also see [#250 ](https://github.com/DestinationHome/Destination-Home-Online/issues/250)

**Comment by CamoRF** [comment]
Issue was resolved, was related to broken rewards at Acorn and another space. (See Discord ticket cant-get-rewards)
