### ISSUE TITLE
Music not working in Pier Park

### ISSUE THREAD

**Issue by CamoRF** [DestinationHome/Destination-Home-Online#265]
**Describe the bug**

**To Reproduce**

1. Go to Pier Park
2. Walk up to this area in the screenshot
3. Music isn't playing

**Expected behavior**
Music is supposed to play in this area, it works in the version that has the Ratchet and Clank statue.

**Screenshots & Video Documentation**
![rpcs3 2023-07-24 15-39-35](https://github.com/DestinationHome/Destination-Home-Online/assets/113881920/e0bebcb2-f1fb-4e6e-8c73-c560700d65cd)

# Client Information:
**Region:** SCEA
**Country:** Australia
**Platform:** RPCS3
**Firmware Type:** OFW

**Additional context**
Multiple people have reported that the music works in the version of the space that has the ratchet and clank statue.

**Comment by Toykyle** [comment]
The music player should now work in the version without the R&C Statue. You'll have to clear cache for it to work however.

**Comment by CamoRF** [comment]
> The music player should now work in the version without the R&C Statue. You'll have to clear cache for it to work however.

Tested it and it works, I'll close the issue. Thanks!
