### ISSUE TITLE
Midway rewards not working

### ISSUE THREAD

**Issue by Amyym** [DestinationHome/Destination-Home-Online#269]
Midway 1 2 and 3 gave rewards other night when it was added, then yesterday it stopped giving rewards all together, i tried many of the minigames, and nothing, also delated save data and cleared cache, but did not do a difference, i managed to get rewards from other spaces, which was not a issue, on playstation 3 NA region!

**Comment by I-Knight-I** [comment]
Rewards work fine at The Midway. This'll be the result of a broken reward in your inventory from visiting spaces not yet reviewed.

You'll need to send me your TICKET.LST file from your PS3, otherwise I have no way of knowing.

**Comment by Amyym** [comment]
Meaning, The spaces i been visiting? and how do i do that, As i have not
recived any rewards from the spaces i been visiting anyway, and all other
spaces works fine as my private spaces that has rewards i recive those, is
only midway that i don't recive from

**Comment by I-Knight-I** [comment]
If a reward is broken but it attempts to give it to you and fails, it'll store it in your TICKET.LST file. The next time you start your game, it'll try to give that reward to you again. Whilst it's constantly trying to give it to you, certain other rewards won't be able to be redeemed. Some others may still get through but it's largely a gamble and those newer rewards might outright disappear at a later point.

When you're given a broken reward (usually the result of scenes from different regions), you won't get a notification that you've received anything. It'll just keep spamming it silently.

Your TICKET.LST file is in your NPIA00005DATA folder. You'll likely need to use HEN/HFW to extract it with multiMAN, zip-it-up and then send it here or on Discord.

**Comment by Amyym** [comment]
How do i do that? As i am on ofw i am nit tech saby when it comes to that
stuff - _-is there a guide or something?

**Comment by I-Knight-I** [comment]
If you want, you can open a ticket and we'll walk you through it on Discord :)

Otherwise, it's the same process you did to get PS Home installed in the first place.

**Comment by Amyym** [comment]
I will try clear cache once more if that does not work i make a ticket!

**Comment by Amyym** [comment]
how do i open a ticket on discord?

**Comment by CamoRF** [comment]
> 

Click "Create ticket" in the #request-support channel

**Comment by I-Knight-I** [comment]
This was resolved.
