### ISSUE TITLE
Novus Prime Level 30 Reward

### ISSUE THREAD

**Issue by panos92-deg** [DestinationHome/Destination-Home-Online#270]
Hello, I reached level 30 on Novus Prime and it should have unlocked me the commander torso. But it didn't.

<img width="139" alt="image" src="https://github.com/DestinationHome/Destination-Home-Online/assets/85350673/59e60032-c951-4da6-b623-fbb4eb85e068">

Platform: PS3
Region: Europe
Firmware: HFW

**Comment by CamoRF** [comment]
Fixed now
