### ISSUE TITLE
Assassians Creed apartment link to Abstergo labs

### ISSUE THREAD

**Issue by BJHBNade** [DestinationHome/Destination-Home-Online#273]
**Describe the bug**

link to Abstergo labs in Assassians creed apartment does not work

**Screenshots & Video Documentation**
![image](https://github.com/DestinationHome/Destination-Home-Online/assets/243883/8f86f093-4d0c-452b-8991-4ce4e9725c13)

# Client Information:
**Region:** [SCEA]
**Country:** US
**Platform:** [PS3]
**Firmware Type:** [HFW]

**Comment by NagatoDEV** [comment]
Try clearing cache, I re-routed to the US version which works on RPCS3 & PS3. @BJHBNade

**Comment by CamoRF** [comment]
Tested on my end and it's fixed now
