### ISSUE TITLE
NA bowling alley incorrect sound locations

### ISSUE THREAD

**Issue by blake1725** [DestinationHome/Destination-Home-Online#280]
sound is broken in the wrong place no sound by TVs, the TVs sound plays in the middle of the space

**Comment by CamoRF** [comment]
I confirmed this issue, at the EU version the sound is located near the screens while at the NA version it is in the middle of the space and the sounds overlap during the minigame.

**Comment by CamoRF** [comment]
Closed as we changed the bowling alley in nav to EU version which doesn't have this issue.
