### ISSUE TITLE
I get an error on the first loading screen

### ISSUE THREAD

**Issue by surume0901** [DestinationHome/Destination-Home-Online#289]
@![IMG_0589](https://github.com/DestinationHome/Destination-Home-Online/assets/145712121/1df50dc8-b7b9-4d25-8e74-aba39959b117)

platform:RPCS3

**Comment by NagatoDEV** [comment]
Hi @surume0901 the following error:

`Z(11, -2)`

Is a whitelist error. Please create a ticket in our [Discord](https://discord.com/invite/QguSBT3) to create a ticket so we can further assist you. Plus please provide the following information in our ticket:

# Client Information:
**Region:** [SCEA, SCEE, SCEJ, SCEAsia, Other]
**Country:** 
**Platform:** [PS3, RPCS3]
**Firmware Type:** [OFW, HFW, CFW]

**Comment by surume0901** [comment]
Thank you for your response! Where can I whitelist something on discord?

**Comment by JustGameGuy** [comment]
@CaptainThrillsDev  Close
