### ISSUE TITLE
Can't whitelist on discord

### ISSUE THREAD

**Issue by surume0901** [DestinationHome/Destination-Home-Online#290]
It says that the method is to enter a command into the BOT, but like the example, I obtained /beta info, [platform] and [region], and then I also obtained RPCD3 and JAPAN, but there was no response. I can't send messages again, what's the reason?

[platform]RPCS3

[region]JAPAN

[userame]surumr0901

[Firm Ware type] OFW

**Comment by xJeris** [comment]
This should be handled via a ticket on discord. closing.
