### ISSUE TITLE
Red Bull machine at house of skate personal space

### ISSUE THREAD

**Issue by Cubbles98** [DestinationHome/Destination-Home-Online#291]
**Describe the bug**
It just breaks and dosent load
**To Reproduce**
Play it and it immediately kicks you saying activity is unavailable 

**Expected behavior**

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** [SCEA, SCEE, SCEJ, SCEAsia, Other]
**Country:** 
**Platform:** [PS3, RPCS3]
**Firmware Type:** [OFW, HFW, CFW]
SCEA
NA
PS3 
OFW
**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by xJeris** [comment]
@Cubbles98 can you please update your ticket with your region, platform, firmware? Thanks.

**Comment by Cubbles98** [comment]
Edited

**Comment by CamoRF** [comment]
Duplicate issue: [266](https://github.com/DestinationHome/Destination-Home-Online/issues/266)
