### ISSUE TITLE
Playground Boombox

### ISSUE THREAD

**Issue by KillerHunter98** [DestinationHome/Destination-Home-Online#303]
My identity

**Region:** [SCEE]    
**Country:** [Germany]
**Platform:** [PS3]
**Online ID:** [KillerHunter__98]
**Firmware Type:** [HFW]

I have a problem on Playstation Home that I can't place the Playground Boombox, after I select it my console freezes which happens exactly the same as in the video with my buddy "HomelanderOfThe7".

"The more I try it happens again and again" 
This has to happen to everyone. I would be happy if you could fix it

kind regards, killerhunter ^^

https://github.com/DestinationHome/Destination-Home-Online/assets/155995129/5d12bece-b2e9-43a9-a2d3-9d2a4e5a75c0

**Comment by CamoRF** [comment]
https://github.com/DestinationHome/Destination-Home-Online/issues/26
