### ISSUE TITLE
Luxorious tropical paradise beach crib missing item

### ISSUE THREAD

**Issue by Neri99** [DestinationHome/Destination-Home-Online#310]

**Comment by Neri99** [comment]
missing the ladder climb item 
![image](https://github.com/DestinationHome/Destination-Home-Online/assets/129874297/590408ac-fcce-44b3-b036-1cbf5bc370c7)

**Comment by NagatoDEV** [comment]
@Neri99 

@Toykyle and I fixed this bug can you can confirm if this interactive object works for this scene.

**Comment by Neri99** [comment]
fixed thankyou
