### ISSUE TITLE
Diamond beach infinite loading loop

### ISSUE THREAD

**Issue by Piloun1** [DestinationHome/Destination-Home-Online#316]
Can't access the private space because of an infinite loading loop

# Client Information:
 SCEE
Belgium
PS3
OFW
![20240428_224614](https://github.com/DestinationHome/Destination-Home-Online/assets/168375206/a727178e-347d-47d1-8277-f85bf0c40e5a)

**Comment by ZephyrCodesStuff** [comment]
Closing because fixed
