### ISSUE TITLE
RC Rally progress reset

### ISSUE THREAD

**Issue by TheRealVT97** [DestinationHome/Destination-Home-Online#323]
If I complete some achievement and unlock a new track/RC part then I change map, everything resets

1. Go to RC Rally
2. Play and complete an achievement to unlock parts/new tracks
3. change map then come back
4. Eeverything should be reset

Expected behavior
After I complete an achievement every progress should remain ofc

Region: SCEE
Country: Italy
Platform: PS3
Firmware Type: CFW

**Comment by xJeris** [comment]
RC Rally doesn't save data currently. That was announced at the time it was released. Eventually it will have saves added.

![image](https://github.com/DestinationHome/Destination-Home-Online/assets/85350673/c1354c6a-26b7-4ea1-9f51-44f77aae98a7)
