### ISSUE TITLE
Tron Apartment Crash

### ISSUE THREAD

**Issue by xXReimuHakureiXx** [DestinationHome/Destination-Home-Online#324]
Playstation Home locks up and crashes when I enter the window room of the Tron apartment where the video player is. The video player attempts to load a video and I have reason to believe that the attempt to load the video is what causes Playstation Home to lock up and crash.

**To Reproduce**

1. Go to the room with the video player and a large window that shows the light cycle racers.

**Expected behavior**

I would expect Tron Evolution content to be shown on the video player.
 
# Client Information:
Region: SCEA
Country: US
Platform: RPCS3
Firmware Type: OFW

**Comment by xJeris** [comment]
Did not crash for me on RPCS3. However, the video does not load.

**Comment by Toykyle** [comment]
Can you clear cache and try it now?

**Comment by xJeris** [comment]
@xXReimuHakureiXx Please clear cache and try to load the Tron Apt again. Thanks.

I have also tested and the video is now working.

**Comment by xJeris** [comment]
Closing as fixed.
