### ISSUE TITLE
Inventory Items not appearing 

### ISSUE THREAD

**Issue by Tiff2serious** [DestinationHome/Destination-Home-Online#34]
**Describe the bug**
 Most Items don't appear when, searching, same results when in storage box. Some will have a question mark in the box. 

**To Reproduce**

**Expected behavior**
For the Items to appear

**Screenshots & Video Documentation**
![20221029_044413](https://user-images.githubusercontent.com/108475784/198912183-cc070d54-5e6d-4512-934c-ac596e79ee03.jpg)

![20221029_044756](https://user-images.githubusercontent.com/108475784/198912233-db3ca7bf-b5ce-4555-b256-d3e6d5dee957.jpg)

![20221029_044856](https://user-images.githubusercontent.com/108475784/198912244-b184f374-22c8-459e-b7b0-83d50c8e29e6.jpg)

# Client Information:
**Region:** North America 
**Country:** US
**Platform:** PS3
**Firmware Type:** HFW

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by I-Knight-I** [comment]
Same issue as #35

**Comment by Tiff2serious** [comment]
Still getting the same results for inventory, clothing, furniture, ornaments, etc.
