### ISSUE TITLE
how to run on linux?

### ISSUE THREAD

**Issue by Ilia1** [DestinationHome/Destination-Home-Online#4]
I use rpcs3 from AppImage. When I run it offline, it says "network error"
When I start online, the emulator freezes.

 - Firmware Version: https://github.com/DestinationHome/Destination-Home-Online/releases/download/V1.00/PS3UPDAT.PUP
 - Custom RPCS3 Client Version: 0.0.22-13651

**Comment by NagatoDEV** [comment]
Hey Ilia1, I assume you running the offline client? This repo is just for future online bugs. I assume if you want to run Home's offline client you can set up a virtual machine on your Linux Distro to run Home via Windows 10/11. Alternatively, I recommend for you ensure that your PC specs are compliant with the RPCS3 [Quick-start guide](https://rpcs3.net/quickstart).

I would also make sure that you utilize the latest [AppImage](https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-aaef4a2d5b605f5600c547e12da9ae42eaefe75e/rpcs3-v0.0.22-13654-aaef4a2d_linux64.AppImage).

Plus if you can send logs, it'll help me debug your issue.

**Comment by Ilia1** [comment]
I did not find where to write about the offline client, so I wrote here. And in the end I want to run online as well.
If I understand correctly, then you modified RPCS3 to work offline client?
[RPCS3.log](https://github.com/DestinationHome/Destination-Home-Online/files/8793908/RPCS3.log)
[config.yml.txt](https://github.com/DestinationHome/Destination-Home-Online/files/8793913/config.yml.txt)

**Comment by I-Knight-I** [comment]
@Ilia1 This isn't the place to be asking about the offline client. You're welcome to join our Discord to request help:

https://discord.com/invite/QguSBT3

The online is not yet released.
