### ISSUE TITLE
Missing Personal Space Club Fight Night by EA Games

### ISSUE THREAD

**Issue by DementedKid** [DestinationHome/Destination-Home-Online#42]
Missing personal space Club Fight Night

# Client Information: Demented-_-Kid
**Region: NA
**Country: USA
**Platform: PS3
**Firmware Type: OFW

**Comment by NagatoDEV** [comment]
Will take a look into this issue soon. I know we already have this scene, we just need to make sure it's compatible with our current client for PS3/RPCS3 users.

**Comment by NagatoDEV** [comment]
This scene is a **Public Space**, which will be added throughout our other testing phases.
