### ISSUE TITLE
Sackboy companion doesn't load

### ISSUE THREAD

**Issue by I-Knight-I** [DestinationHome/Destination-Home-Online#5]
**Describe the bug**
Sackboy companion doesn't load when selecting it. Regional issue?

**To Reproduce**

1. Go to 'Personal' -> 'My Inventory' -> Sackboy Companion
2. No Sackboy companion is spawned/visible

**Expected behavior**
Sackboy companion works/loads/is visible

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Sackboy companion</h1>

@TheOrbOfDestiny @I-Knight-I 

The Sackboy companion should load up just fine now.

![NPIA00005_screenshot_2022_10_27_03_05_19](https://user-images.githubusercontent.com/67494727/198216593-fc0a48fa-7a57-489c-9e1a-b71f5bdb5cf3.png)

![NPIA00005_screenshot_2022_10_27_03_05_33](https://user-images.githubusercontent.com/67494727/198216642-56557326-9d3e-47b3-98e0-bbe0b012944c.png)

**Client Tested:** RPCS3
**Region:** NA
**Notes:** *Should* be working on EU accounts as I don't think object was region locked.
