### ISSUE TITLE
Underwater Apartment has no thumbnail in the rewards list

### ISSUE THREAD

**Issue by I-Knight-I** [DestinationHome/Destination-Home-Online#7]
**Describe the bug**
Underwater Apartment has no thumbnail in the rewards list

**To Reproduce**

1. Press START in-game
2. Go to Personal
3. Go to My Rewards
4. Scroll until you see 'Underwater Apartment'

**Expected behavior**
Underwater apartment has a thumbnail

**Screenshots & Video Documentation**

![image](https://user-images.githubusercontent.com/26165117/198272007-2c268786-b7ff-4104-bc69-f1fde80d4f64.png)

# Client Information:
**Region:** SCEA
**Country:** USA
**Firmware Version:** 4.89

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Missing Icon for Underwater Apartment </h1>

@I-Knight-I 

Users should be able to view the missing icon in their rewards list. 

![NPIA00005_screenshot_2022_11_01_21_12_22](https://user-images.githubusercontent.com/67494727/199371609-9312fbde-31b6-4727-9972-8be91fb06e66.png)

**Client Tested:** RPCS3
**Region:** NA & EU
**Notes:** None.
