### ISSUE TITLE
Red Bull Air Race

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [DestinationHome/Destination-Home-Online#70]
**Describe the bug**

Unable to enter
No Tile image in Navigation menu

# Client Information:
**Region:** SCEA
**Country:** 
**Platform:** RPCS3
**Firmware Type:** OFW

**Comment by NagatoDEV** [comment]
RESIDENT EVIL 5 Studio Lot, this version you've clicked on was from the Asian region. Will keep this issue open as I will close it once we get it's correct version for our server.

**Comment by NagatoDEV** [comment]
Hi Jedi, try clearing your cache to see if you are able to boot into Red Bull Air Race.

![NPIA00010_screenshot_2023_01_30_23_26_28](https://user-images.githubusercontent.com/67494727/215664813-4d12f084-2bab-4e8c-8005-19249e013620.png)
