### ISSUE TITLE
Resident Evil 5 Studio Lot

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [DestinationHome/Destination-Home-Online#71]
**Describe the bug**

Unable to enter, does not download.

# Client Information:
**Region:** SCEA
**Platform:**  RPCS3
**Firmware Type:** [OFW, HFW, CFW]

**Comment by NagatoDEV** [comment]
RESIDENT EVIL 5 Studio Lot, this version you've clicked on was from the Asian region. Will keep this issue open as I will close it once we get its correct version for our server.

**Comment by I-Knight-I** [comment]
Fixed according to #100
