### ISSUE TITLE
Whimsy Hollow has no thumbnail in the rewards list

### ISSUE THREAD

**Issue by I-Knight-I** [DestinationHome/Destination-Home-Online#8]
**Describe the bug**
Whimsy Hollow has no thumbnail in the rewards list

**To Reproduce**

1. Press START in-game
2. Go to Personal
3. Go to My Rewards
4. Scroll until you see 'Whimsy Hollow

**Expected behavior**
Whimsy Hollow has a thumbnail

**Screenshots & Video Documentation**
![image](https://user-images.githubusercontent.com/26165117/198272398-4970f080-cb4a-429b-9431-8311c91f83eb.png)

# Client Information:
**Region:** SCEA
**Country:** USA
**Firmware Version:** 4.89

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Missing Icon for Whimsy Hollow</h1>

@I-Knight-I 

Users should be able to view the missing icon in their rewards list. 

![NPIA00005_screenshot_2022_11_01_21_22_33](https://user-images.githubusercontent.com/67494727/199372575-55765aa8-ea00-4003-a8e1-2fb801b3fbff.png)


**Client Tested:** RPCS3
**Region:** NA & EU
**Notes:** None.
